import { CLIENT_ERROR_CODES } from "./errors";
import { UNKNOWN_ERROR_CODE, UNKNOWN_FIELD_ERROR_CODE } from "./errorMessage";

/**
 * 화면 문구가 있어야 하는 오류 코드 목록(FR-154, SC-024). 문구는 4개 언어 `errors.json`의 `{code}` 키다.
 * - backend `resultCode`: contracts/api.md "오류 코드" 표의 001 코드 + 002 코드(NOTIFICATION_NOT_FOUND,
 *   CANNOT_SUBSCRIBE_OWN_BLOG) + 공통 처리 코드(backend `ErrorCode`).
 *   003 코드(주제·추천·제외·설정, 003 contracts/api.md)와 001 표의 릴리스 노트 코드 5개(003 구현 때 더함, 001 결정 8번)
 * - front가 정하는 코드(BACKEND_UNAVAILABLE 등)와 모르는 코드용 UNKNOWN
 * 새 코드를 쓰면 여기와 4개 언어 errors.json에 같은 PR에서 넣는다(tests/unit/i18n/errorCodes.test.ts).
 */
export const API_ERROR_CODES = [
  // 400
  "VALIDATION_FAILED",
  "THUMBNAIL_SIZE_NOT_ALLOWED",
  "PASSWORD_RESET_TOKEN_INVALID",
  "CURRENT_PASSWORD_MISMATCH",
  // 401
  "UNAUTHENTICATED",
  "INVALID_CREDENTIALS",
  "REFRESH_INVALID",
  // 403
  "FORBIDDEN",
  "ORIGIN_NOT_ALLOWED",
  // 404
  "BLOG_NOT_FOUND",
  "POST_NOT_FOUND",
  "DRAFT_NOT_FOUND",
  "CATEGORY_NOT_FOUND",
  "COMMENT_NOT_FOUND",
  "MEDIA_NOT_FOUND",
  "NOTIFICATION_NOT_FOUND",
  "NOT_FOUND",
  "TOPIC_NOT_FOUND",
  "CURATION_NOT_FOUND",
  "PORTAL_EXCLUSION_NOT_FOUND",
  "SETTING_NOT_FOUND",
  "RELEASE_NOTE_NOT_FOUND",
  // 004 (004 contracts/api.md "오류 코드")
  "POST_PASSWORD_MISMATCH",
  "POST_LOCKED",
  "PASSWORD_ATTEMPTS_EXCEEDED",
  "SCHEDULE_NOT_ALLOWED",
  "POST_NOT_SCHEDULED",
  "GUEST_PASSWORD_MISMATCH",
  "GUESTBOOK_DISABLED",
  "GUESTBOOK_ENTRY_NOT_FOUND",
  "EXPORT_LIMIT_EXCEEDED",
  "EXPORT_NOT_FOUND",
  "CANNOT_BLOCK_SELF",
  "USER_NOT_FOUND",
  "BLOCK_NOT_FOUND",
  // 005 (005 contracts/api.md "오류 코드")
  "CAPTCHA_FAILED",
  "CAPTCHA_REQUIRED",
  "REPORT_TARGET_NOT_FOUND",
  "REPORT_NOT_FOUND",
  "CONTENT_NOT_FOUND",
  "BLOG_RESTRICTED",
  "BANNED_WORD_NOT_FOUND",
  "TRACKBACK_NOT_FOUND",
  "REPORT_ALREADY_EXISTS",
  "REPORT_ALREADY_RESOLVED",
  "REPORT_ALREADY_TARGETED",
  "POST_HIDDEN",
  "USER_NOT_ACTIVE",
  "LAST_SUPER_ADMIN",
  "BANNED_WORD_EXISTS",
  "CANNOT_REPORT_OWN_CONTENT",
  "REPORT_TARGET_REQUIRED",
  "REPORT_ACTION_NOT_ALLOWED",
  "CANNOT_SUSPEND_SELF",
  "DUPLICATE_CONTENT_SPAM",
  "TRACKBACK_NOT_ALLOWED",
  // 007 (007 contracts/api.md "오류 코드 (007에서 추가)"). params(reason·result 등)별 문구는 `external` namespace
  "EXTERNAL_FEED_URL_NOT_ALLOWED",
  "EXTERNAL_FEED_NOT_FOUND",
  "EXTERNAL_FEED_UNREADABLE",
  "EXTERNAL_BLOG_ALREADY_REGISTERED",
  "EXTERNAL_BLOG_LIMIT_EXCEEDED",
  "EXTERNAL_BLOG_NOT_FOUND",
  "EXTERNAL_BLOG_STATE_CONFLICT",
  "EXTERNAL_BLOG_OWNERSHIP_REQUIRED",
  "EXTERNAL_VERIFICATION_NOT_FOUND",
  "EXTERNAL_VERIFICATION_EXPIRED",
  "EXTERNAL_VERIFICATION_CODE_NOT_FOUND",
  "EXTERNAL_POST_NOT_FOUND",
  "CLASSIFICATION_REVIEW_NOT_FOUND",
  "CLASSIFICATION_REVIEW_CLOSED",
  "TOPIC_MAPPING_RULE_KEYWORD_TAKEN",
  // 409
  "EMAIL_TAKEN",
  "HANDLE_TAKEN",
  "CATEGORY_NAME_TAKEN",
  "BLOG_LIMIT_EXCEEDED",
  "LAST_BLOG_CANNOT_BE_DELETED",
  "POST_NOT_PUBLISHED",
  "TOPIC_SLUG_TAKEN",
  "CURATION_LIMIT_EXCEEDED",
  "RELEASE_NOTE_VERSION_TAKEN",
  "RELEASE_NOTE_REVISION_CONFLICT",
  "RELEASE_NOTE_ONCE_PUBLISHED",
  // 413, 415
  "MEDIA_TOO_LARGE",
  "MEDIA_TYPE_NOT_ALLOWED",
  // 422
  "HANDLE_RESERVED",
  "HANDLE_INVALID",
  "TAG_LIMIT_EXCEEDED",
  "CATEGORY_DEPTH_EXCEEDED",
  "REPLY_DEPTH_EXCEEDED",
  "COMMENTS_DISABLED",
  "POST_NOT_IN_TRASH",
  "POST_CONTENT_EMPTY",
  "TERMS_VERSION_OUTDATED",
  "CANNOT_SUBSCRIBE_OWN_BLOG",
  "TOPIC_NOT_SELECTABLE",
  "TOPIC_DEPTH_EXCEEDED",
  "POST_NOT_PORTAL_ELIGIBLE",
  "RELEASE_NOTE_VERSION_LOCKED",
  "CANNOT_CHANGE_OWN_ROLE",
  // 423, 429
  "ACCOUNT_LOCKED",
  "MEDIA_TEMP_QUOTA_EXCEEDED",
  // 공통 처리(표에 없는 HTTP 오류): 405, 415(요청 형식), 429(요청 제한), 500
  "METHOD_NOT_ALLOWED",
  "UNSUPPORTED_MEDIA_TYPE",
  "TOO_MANY_REQUESTS",
  "INTERNAL_ERROR",
] as const;

/** 화면 문구가 있어야 하는 전체 오류 코드(backend + front + 모르는 코드) */
export const ERROR_CODES = [
  ...API_ERROR_CODES,
  ...Object.values(CLIENT_ERROR_CODES),
  UNKNOWN_ERROR_CODE,
] as const;

/** 입력 검증 오류 코드(`header.fieldErrors[].code`). 문구는 `errors.json`의 `fieldErrors.{code}` 키다. */
export const FIELD_ERROR_CODES = [
  "REQUIRED",
  "TOO_LONG",
  "TOO_SHORT",
  "TOO_LARGE",
  "TOO_SMALL",
  "INVALID_FORMAT",
  "PASSWORD_WEAK",
  "PASSWORD_CONFIRM_MISMATCH",
  // 005: 이름류·본문류의 거부 금칙어(FR-143). 어느 단어인지는 알려 주지 않는다.
  "BANNED_WORD",
  UNKNOWN_FIELD_ERROR_CODE,
] as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[number];
